apiVersion: v1
kind: Service
metadata:
  name: t-svc
  labels:
    app: my-test
spec:
  type: NodePort
  ports:
  - name: rtmpp
    port: 1936
    targetPort: 1936
    nodePort: 31936
    protocol: TCP
  - name: http1
    port: 81
    targetPort: 81
    nodePort: 30081
    protocol: TCP
  selector:
    app: my-test