apiVersion: v1
kind: Service
metadata:
  name: t-svc
  labels:
    app: my-test
spec:
  type: NodePort
  ports:
  - name: rtmpp
    port: 1935
    targetPort: 1935
    nodePort: 30000
    protocol: TCP
  - name: http1
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-test