apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-test
spec:
  containers: 
  - name: test
    image: wito2403/rtmp_cpu:v3_1
    ports:
    - containerPort: 1935
    - containerPort: 80