apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-test
spec:
  volumes: 
  - name: config
    configMap:
      name: port-cm
      items:
        - key: c1
          path: cpu-1s
  containers: 
  - name: test
    image: wito2403/rtmp_cpu:v3_1
    ports:
    - containerPort: 1936
    - containerPort: 81
    volumeMounts:
    - name: config
      mountPath: /usr/local/nginx/conf/nginx.conf
      subPath: cpu-1s